# Generated by Django 4.2.4 on 2025-01-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('option', 'Option'), ('multi_option', 'Multi Option')], default='text', max_length=16),
        ),
    ]
